version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_files:
  - src: files/ansible.cfg
    dest: configs
  - src: files/pip.conf
    dest: configs
  - src: files/ca-bundle.crt
    dest: configs

additional_build_steps:
  prepend_base:
    - COPY _build/configs/ca-bundle.crt /usr/share/pki/ca-trust-source/anchors/
    - RUN update-ca-trust
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg ~/.ansible.cfg
    - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://ans-01.corp.ritcsusa.com/api/galaxy/
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://ans-01.corp.ritcsusa.com/api/galaxy/
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
options:
  package_manager_path: /usr/bin/microdnf
